batch: 1
data: lfw
data_path: ./input/data
device: cuda:0
half: false
mode: adv
model: arcface
name: adv
num_classes: 1000
pretrained: null
project: arcface
save_dir: ./output
selected_samples: 10
verbose: true
workers: 0
